### ISSUE TITLE
Blinded settings don't apply to tokens that are not linked to actor data

### ISSUE THREAD

**Issue by MS-PBS** [kandashi/condition-automation#27]
By not linked to actor data I mean that "Link Actor Data" is unchecked. My test world:

-Foundry 0.7.9
-DnD 5e 1.2.0
-Condition Automation 2.2.2
-No other active modules

Blinded settings apply to linked tokens normally, but the changes to unlinked tokens are not applied at all. If I check the link actor data box, the same token works correctly, until I uncheck the box again.

**Comment by kandashi** [comment]
This is fixed in 2.2.3

**Comment by MS-PBS** [comment]
I'm sorry Kandashi, this issue still exists in 2.2.32, at least on my end.

**Comment by kandashi** [comment]
Sorry about this, it'll teach me for releasing fixes at 2am 😆

**Comment by kandashi** [comment]
What option have you got for the blind setting?

**Comment by MS-PBS** [comment]
1 degree vision. Though I tested the other two (for the perfect vision setting I enabled perfect vision, of course), and none seem to be working.

**Comment by kandashi** [comment]
I believe ive found the issue. If you re-install from this link: https://raw.githubusercontent.com/kandashi/condition-automation/2.2.33/module.json
can you confirm if the issue is fixed for you

**Comment by MS-PBS** [comment]
Yes, it works fine now. The "Enable NPC vision settings" setting seems to do the trick. Tough in reality, it enables the effect for unlinked tokens, rather than NPC tokens. If it is off, it blinds linked NPC tokens, and it won't blind unlinked PC tokens.

**Comment by kandashi** [comment]
Ill chnage that now 👍
